# Generated by Django 4.1.5 on 2024-03-12 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sunburst',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='email',
            new_name='participant_email',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='name',
            new_name='participant_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='client_project',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='points',
            new_name='trend_input',
        ),
        migrations.AddField(
            model_name='response',
            name='readiness_input',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='weighting_input',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
