# Generated by Django 4.1.5 on 2024-03-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='image',
            field=models.ImageField(upload_to='graphs/'),
        ),
    ]
