# Generated by Django 4.1.5 on 2024-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementresponse',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
