# Generated by Django 4.1.5 on 2024-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='category',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
