# Generated by Django 4.1.5 on 2024-03-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0002_element_category_element_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_score_max', models.IntegerField()),
                ('weighting_max', models.IntegerField()),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunbursts.project')),
                ('selected_elements', models.ManyToManyField(to='sunbursts.element')),
            ],
        ),
    ]
