# Generated by Django 4.1.5 on 2024-03-14 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0002_element_ref_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementresponse',
            old_name='readiness_input',
            new_name='readiness',
        ),
        migrations.RenameField(
            model_name='elementresponse',
            old_name='trend_input',
            new_name='trendneeded',
        ),
        migrations.RenameField(
            model_name='elementresponse',
            old_name='weighting_input',
            new_name='trendnow',
        ),
        migrations.AddField(
            model_name='elementresponse',
            name='weighting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='element',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='sunbursts.project'),
        ),
        migrations.AlterField(
            model_name='elementresponse',
            name='survey_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_responses', to='sunbursts.surveyresponse'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sunbursts.project'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='sunbursts.project'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='sunbursts.survey'),
        ),
    ]
