# Generated by Django 4.1.5 on 2024-03-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0002_elementresponse_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sunburst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('point_score', models.IntegerField(default=0)),
                ('need_score', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunbursts.project')),
            ],
        ),
    ]
