# Generated by Django 4.1.5 on 2024-03-12 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0002_rename_sunburst_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='readiness_input',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
