# Generated by Django 4.1.5 on 2024-03-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0003_alter_response_readiness_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='trend_input',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='weighting_input',
            field=models.IntegerField(default=0),
        ),
    ]
