# Generated by Django 4.1.5 on 2024-03-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0003_rename_trend_input_elementresponse_trend_needed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementresponse',
            old_name='readiness_input',
            new_name='readiness',
        ),
        migrations.RenameField(
            model_name='elementresponse',
            old_name='trend_needed',
            new_name='trendneeded',
        ),
        migrations.RenameField(
            model_name='elementresponse',
            old_name='trend_now',
            new_name='trendnow',
        ),
        migrations.RenameField(
            model_name='elementresponse',
            old_name='weighting_input',
            new_name='weighting',
        ),
    ]
