# Generated by Django 4.1.5 on 2024-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0003_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='user_selections_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='readiness_score_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='weighting_max',
            field=models.IntegerField(default=20),
        ),
    ]
