# Generated by Django 4.1.5 on 2024-03-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0003_sunburst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunburst',
            name='need_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sunburst',
            name='point_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sunburst',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
