# Generated by Django 4.1.5 on 2024-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0004_alter_sunburst_need_score_alter_sunburst_point_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunburst',
            name='need_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sunburst',
            name='point_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sunburst',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
