# Generated by Django 4.1.5 on 2024-03-12 19:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0004_survey_user_selections_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighting_input', models.IntegerField(default=0)),
                ('trend_input', models.IntegerField(default=0)),
                ('readiness_input', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='project_name',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='project_name',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='element',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='selected_elements',
        ),
        migrations.AddField(
            model_name='element',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunbursts.survey'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunbursts.participant'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunbursts.survey'),
        ),
        migrations.AddField(
            model_name='elementresponse',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunbursts.element'),
        ),
        migrations.AddField(
            model_name='elementresponse',
            name='survey_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunbursts.surveyresponse'),
        ),
    ]
