# Generated by Django 4.1.5 on 2024-03-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0005_elementresponse_surveyresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='survey',
        ),
        migrations.AddField(
            model_name='survey',
            name='selected_elements',
            field=models.ManyToManyField(to='sunbursts.element'),
        ),
    ]
