# Generated by Django 4.1.5 on 2024-03-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunbursts', '0005_alter_sunburst_need_score_alter_sunburst_point_score_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sunburst',
            new_name='SunburstElement',
        ),
    ]
